### ISSUE TITLE
Add old-style footer to site

### ISSUE THREAD

**Issue by BretFisher** [BretFisher/ghost-edition#5]
the current `footer.hbs` of the edition theme is too minimal. We would like a more expanded footer that we can add links over time, similar to [ghost.org](https://ghost.org) footer or [docker.com](https://docker.com) footer. 

Colors can stay the same as page.

For now, assume three vertical lists with these titles and links. Responsiveness would have these 3 vertical lists consolidate to one vertical on mobile. Since Ghost secondary nav won't help with multiple lists, let's avoid secondary nav and just hardcode these in the partial template (unless you know of a better way).

## Learn Container DevOps
Udemy Courses /courses
Podcast /podcast
YouTube https://www.youtube.com/c/BretFisherDockerandDevOps
Newsletter /newsletter
Docker Resources /docker

## Community
DevOps Discord Server https://devops.fan
Patreon High Fivers Membership https://patreon.com/bretfisher
Upcoming YouTube Live Streams https://www.youtube.com/c/BretFisherDockerandDevOps/videos?view=2&sort=dd&live_view=502&shelf_id=0
Ask Me Anything https://github.com/BretFisher/ama

## Find Me
GitHub https://github.com/BretFisher
Twitter https://twitter.com/BretFisher
Instagram https://www.instagram.com/bretfisher/
Linkedin https://www.linkedin.com/in/bretefisher

Inspiration:

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/792287/153952200-aa6a01dc-f4b2-4ee6-9f99-0ad926b019c3.png">

**Comment by kingRayhan** [comment]
Would you please put a screenshot of a footer for getting inspiration?
